name: Cleanup Pull Requests
on:
    pull_request:
      types: [opened, edited, ready_for_review]
      
jobs:
    label: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Add "needs review" label if no reviewers or assignees
          uses: actions/github-script@v6
          with:
            script: |
              const pr = github.context.payload.pull_request;
              const owner = github.context.repo.owner;
              const repo = github.context.repo.repo;
  
              // Check if there are no reviewers and no assignees
              if (pr.requested_reviewers.length === 0 && pr.assignees.length === 0) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: pr.number,
                  labels: ['Review Needed']
                });
              }

    mark-submissions:
        runs-on: ubuntu-latest
        permissions: 
          pull-requests: write
          issues: write
        steps: 
          - name: Close Stale Issues
            uses: actions/stale@v9.0.0
            with:
              stale-pr-message: >
                Hi, if you need any assistance, please don't hesitate to ask here or in #electronics on Slack. This pull request is being marked as 'Stalled' for now and will be closed in 3 days if there is no activity.
              close-pr-message: >
                  This pull request has been inactive for some time and has therefore been closed. Feel free to create a new one when you're ready.
              # The number of days old an issue or a pull request can be before marking it stale. Set to -1 to never mark issues or pull requests as stale automatically.
              days-before-issue-stale: 30
              days-before-pr-stale: 7
              # The number of days to wait to close an issue or a pull request after it being marked stale. Set to -1 to never close stale issues or pull requests.
              days-before-close: 7
              # The number of days to wait to close an issue after it being marked stale. Set to -1 to never close stale issues. Override "days-before-close" option regarding only the issues.
              days-before-issue-close: -1
              # The label to apply when an issue is stale.
              stale-issue-label: "Stalled"
              # The labels that mean an issue is exempt from being marked stale. Separate multiple labels with commas (eg. "label1,label2").
              exempt-issue-labels: "Dev"
              exempt-pr-labels: "Dev"
              # The label to apply when a pull request is stale.
              stale-pr-label: "Stalled"
              # Only pull requests with at least one of these labels are checked if stale. Defaults to `` (disabled) and can be a comma-separated list of labels. Override "any-of-labels" option regarding only the pull requests.
              any-of-pr-labels: Submission
              include-only-assigned: true
